[package]
name = "nethsm_pkcs11"
version = "0.1.0"
edition = "2021"

[lib]
name = "nethsm_pkcs11"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.80"
cryptoki-sys = "0.1.6"
log = "0.4.19"
env_logger = "0.10.0"